[cli]
username = "admin"
base_url = "https://pulp.tooling.provider.test"
password = "Pa55w0rd"
api_root = "/pulp/"
domain = "default"
headers = []
cert = ""
key = ""
verify_ssl = false
format = "json"
dry_run = false
timeout = 0
verbose = 0
