volumes:
  pulp-settings: null
  pulp-pgsql: null
  pulp-storage: null
  pulp-containers: null

secrets:
  pulp_key:
    file: ../vault/certs/pulp.tooling.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.pem
  pulp_crt:
    file: ../vault/certs/pulp.tooling.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.crt

services:
  pulp:
    container_name: pulp.tooling.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}
    build: .
    restart: unless-stopped
    init: false
    stop_signal: SIGINT
    stop_grace_period: 15s
    # user: '${default_user}'
    environment:
      - CONTENT_ORIGIN=https://pulp.tooling.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}
      - PULP_UI=true
      - PULP_SECRET_KEY=secret
      - PULP_HTTPS=true
      - DOMAIN_NAME_SL=${DOMAIN_NAME_SL}
      - DOMAIN_NAME_TL=${DOMAIN_NAME_TL}
    secrets:
      # - source: ca_crt
      #   target: /etc/ssl/certs/cacert.pem
      - source: pulp_key
        target: /etc/pki/tls/private/pulp_webserver.key
      - source: pulp_crt
        target: /etc/pki/tls/certs/pulp_webserver.crt
    volumes:
      - 'pulp-settings:/etc/pulp'
      - 'pulp-pgsql:/var/lib/pgsql'
      - 'pulp-storage:/var/lib/pulp'
      - 'pulp-containers:/var/lib/containers'
    devices:
      - '/dev/fuse'
    networks:
      internal:
        ipv4_address: 172.16.11.10
    ports:
      - '443:443'
    expose:
      - 8002
    depends_on:
      - keycloak
      - cicdtoolbox-db
