volumes:
  ldap_data: null

secrets:
  ldap_key:
    file: ../vault/certs/ldap.iam.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.pem
  ldap_crt:
    file: ../vault/certs/ldap.iam.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.crt

services:
  ldap:
    container_name: ldap.iam.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}
    build: .
    restart: unless-stopped
    hostname: ldap
    expose:
      - '3890'
    ports:
      - '17170:17170'
    secrets:
      - source: ldap_key
        target: /data/key.pem
      - source: ldap_crt
        target: /data/cert.crt
    volumes:
      - './data:/data'
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Amsterdam
      - LLDAP_LDAP_BASE_DN=dc=provider,dc=test
      - LLDAP_HTTP_URL = "http://ldap.iam.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}"
      - LLDAP_LDAP_USER_PASS='${ldap_admin_password}'
      # - LLDAP_KEY_FILE = "/data/key.pem"
      # - LLDAP_LDAPS_OPTIONS__ENABLED = TRUE
      # - LLDAP_LDAPS_OPTIONS__PORT = 6360
      - LLDAP_LDAPS_OPTIONS__CERT_FILE = "/data/cert.crt"
      - LLDAP_LDAPS_OPTIONS__KEY_FILE = "/data/key.pem"
      # - LLDAP_DATABASE_URL=postgres://'${ldap_db_user}':'${ldap_db_password}'@cicdtoolbox-db.internal.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}/ldap
    networks:
      internal:
        ipv4_address: 172.16.8.11
    healthcheck:
      test: 'curl --insecure -fSs http://ldap.iam.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}:17170/login'
      start_period: 60s
      interval: 5s
      timeout: 5s
      retries: 5

