networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.8.0/21

include:
  - cicdtoolbox-db/compose.yaml
  - gitea/compose.yaml
  - jenkins/compose.yaml
  - buildnode/compose.yaml
  - keycloak/compose.yaml
  - lldap/compose.yaml
  - pulp/compose.yaml
  - portainer/compose.yaml
  - vault/compose.yaml

secrets:
  ca_crt:
    file: ./vault/certs/ca.crt

services:
  seleniumffhost:
    container_name: seleniumffhost.internal.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}
    image: 'selenium/standalone-firefox:latest'
    restart: unless-stopped
    expose:
      - 4444
    ports:
      - '7901:7900'
    shm_size: '2gb'
    networks:
      internal:
        ipv4_address: 172.16.10.100
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://seleniumffhost.internal.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}:4444"] 
      interval: 10s
      timeout: 5s
      retries: 3


  seleniumgchost:
    container_name: seleniumgchost.internal.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}
    image: 'selenium/standalone-chrome:latest'
    restart: unless-stopped
    expose:
      - 4444
    ports:
      - '7900:7900'
    shm_size: '2gb'
    networks:
      internal:
        ipv4_address: 172.16.10.101
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://seleniumgchost.internal.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}:4444"] 
      interval: 10s
      timeout: 5s
      retries: 3
