volumes:
  gitea:
    driver: local

secrets:
  gitea_key:
    file: ../vault/certs/gitea.tooling.provider.test.pem
  gitea_crt:
    file: ../vault/certs/gitea.tooling.provider.test.crt

services:
  gitea.tooling.provider.test:
    container_name: gitea.tooling.provider.test
    build: .
    depends_on:
      - cicdtoolbox-db.internal.provider.test
      - keycloak.services.provider.test
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__DOMAIN=gitea.tooling.provider.test
      - 'GITEA__database__USER=${gitea_db_user}'
      - 'GITEA__database__PASSWD=${gitea_db_password}'
    secrets:
      - source: ca_crt
        target: /usr/local/share/ca-certificates/CICD-toolbox-ca.crt
    networks:
      internal:
        ipv4_address: 172.16.11.3
    volumes:
      - 'gitea:/data'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '3000:3000'
    healthcheck:
      test: 'curl --insecure -fSs https://172.16.11.3:3000/api/healthz'
      start_period: 60s
      interval: 5s
      timeout: 5s
      retries: 5
