secrets:
  keycloak_key:
    file: ../vault/certs/keycloak.services.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.pem
  keycloak_crt:
    file: ../vault/certs/keycloak.services.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.crt

services:
  keycloak:
    container_name: keycloak.services.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}
    build: .
    command: ["start"]
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    environment:
      KEYCLOAK_ADMIN: '${local_admin_user}'
      KEYCLOAK_ADMIN_PASSWORD: '${local_admin_password}'
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true' 
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak 
      KC_DB_URL_HOST: cicdtoolbox-db.internal.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL} 
      KC_DB_URL_PORT: 5432 
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: '${keycloak_db_user}'
      KC_DB_PASSWORD: '${keycloak_db_pwd}' 
      KC_HOSTNAME: keycloak.services.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL} 
      KC_HTTPS_CERTIFICATE_FILE: '/etc/x509/https/tls.crt'
      KC_HTTPS_CERTIFICATE_KEY_FILE: '/etc/x509/https/tls.key'
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: 'true' 
      JDBC_PARAMS: ssl=true&sslmode=verify-ca&sslrootcert=/etc/pki/ca-trust/source/anchors/ca.crt
      DOMAIN_NAME_SL: '${DOMAIN_NAME_SL}'
      DOMAIN_NAME_TL: '${DOMAIN_NAME_TL}'
      ORG_NAME: '${ORG_NAME}'
    secrets:
      - source: keycloak_key
        target: /etc/x509/https/tls.key
      - source: keycloak_crt
        target: /etc/x509/https/tls.crt
    networks:
      internal:
        ipv4_address: 172.16.10.11
    expose:
      - 8080
      - 8443
      - 9000
    ports:
      - '8080:8080'
      - '8443:8443'
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s
    depends_on:
      - cicdtoolbox-db
