volumes:
  jenkins_certs: null
  jenkins_data: null
  jenkins_conf: null

secrets:
  jenkins_key:
    file: ../vault/certs/jenkins.tooling.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.pem
  jenkins_crt:
    file: ../vault/certs/jenkins.tooling.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.crt

services:
  jenkins:
    container_name: jenkins.tooling.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}
    build: .
    restart: unless-stopped
    privileged: true
    user: root
    networks:
      internal:
        ipv4_address: 172.16.11.8
    environment:
      - ORG_NAME=${ORG_NAME}
      - CML_URL=https://192.168.32.161
      - CML_USER=${cml_user}
      - CML_PASSWORD=${cml_user_pwd}
      - JENKINS_ANSIBLE_VAULT_ID=${JENKINS_ANSIBLE_VAULT_ID}
      - JENKINS_ANSIBLE_VAULT_PASSWORD=${JENKINS_ANSIBLE_VAULT_SECRET}
      - JENKINS_PULP_USER=jenkins_pulp
      - JENKINS_PULP_PASSWORD=${jenkins_pulp_password}
      - JENKINS_GIT_USER=jenkins_git
      - JENKINS_GIT_PASSWORD=${jenkins_git_password}
      - JENKINS_DEV_LOGON_USER=${default_user}
      - JENKINS_DEV_LOGON_PASSWORD=${jenkins_dev_logon_password}
      - JENKINS_ADMIN_ID=${local_admin_user}
      - JENKINS_ADMIN_PASSWORD=${local_admin_password}
      - DOMAIN_NAME_SL=${DOMAIN_NAME_SL}
      - DOMAIN_NAME_TL=${DOMAIN_NAME_TL}
      - NETCICD_PASSWORD=${default_user_password}
      - GIT_PASSWORD=${local_admin_password}
      - GITEA_IP=172.16.11.3
      - JENKINS_IP=172.16.11.8
      - PULP_IP=172.16.11.9
    secrets:
      - source: jenkins_key
        target: /var/jenkins_home/jenkins.tooling.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.pem
      - source: jenkins_crt
        target: /var/jenkins_home/jenkins.tooling.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.crt
    volumes:
      - 'jenkins_certs:/certs/client'
      - 'jenkins_data:/var/jenkins_home'
      - 'jenkins_conf:/var/jenkins_conf'
    expose: 
      - 8084
      - '50000'
    ports:
      - '8084:8084'
    depends_on:
      - keycloak
    healthcheck:
      test: 'curl --insecure -fSs https://jenkins.tooling.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}:8084/static/%3Canystring%3E/images/svgs/logo.svg'
      start_period: 60s
      interval: 5s
      timeout: 5s
      retries: 5
