volumes:
  vault-config: null
  vault-policies: null
  vault-data: null
  vault-logs: null
  consul-config: null
  consul-data: null

services:
  vault.internal.provider.test:
    container_name: vault.internal.provider.test
    build:
      context: ./vault
      dockerfile: docker/Dockerfile-vault
    depends_on:
      - consul.internal.provider.test
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    networks:
      internal:
        ipv4_address: 172.16.9.5
    expose:
      - 8200
    ports:
      - '8200:8200'
    volumes:
      - 'vault-config:/vault/config'
      - 'vault-policies:/vault/policies'
      - 'vault-data:/vault/data'
      - 'vault-logs:/vault/logs'
    environment:
      - 'VAULT_ADDR=http://vault.internal.provider.test:8200'
      - 'VAULT_API_ADDR=http://vault.internal.provider.test:8200'
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--proxy", "off", "https://vault.internal.provider.test:8200/v1/sys/health?standbyok=true" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s

  consul.internal.provider.test:
    container_name: consul.internal.provider.test
    build:
      context: ./vault
      dockerfile: docker/Dockerfile-consul
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    networks:
      internal:
        ipv4_address: 172.16.9.4
    volumes:
      - 'consul-data:/consul/data'
