volumes:
  portainer-data: null

secrets:
  portainer_key:
    file: ../vault/certs/portainer.monitoring.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.pem
  portainer_crt:
    file: ../vault/certs/portainer.monitoring.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.crt

services:
  portainer:
    container_name: portainer.monitoring.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}
    build: .
    command: --sslcert /etc/ssl/portainer.crt --sslkey /etc/ssl/portainer.key
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    # user: '${default_user}'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - DOMAIN_NAME_SL=${DOMAIN_NAME_SL}
      - DOMAIN_NAME_TL=${DOMAIN_NAME_TL}
      - VIRTUAL_HOST=portainer.monitoring.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}
    secrets:
      - source: ca_crt
        target: /etc/ssl/certs/cacert.pem
      - source: portainer_key
        target: /etc/ssl/portainer.key
      - source: portainer_crt
        target: /etc/ssl/portainer.crt
    volumes:
      - 'portainer-data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      internal:
        ipv4_address: 172.16.13.3
    ports:
      - '9000:9000'
    
