secrets:
  dev_jenkins_secret:
    file: ./Dev_secret.txt
  test_jenkins_secret:
    file: ./Test_secret.txt
  acc_jenkins_secret:
    file: ./Acc_secret.txt
  prod_jenkins_secret:
    file: ./Prod_secret.txt
  build-dev_key:
    file: ./vault/certs/build-dev.delivery.provider.test.pem
  build-dev_crt:
    file: ./vault/certs/build-dev.delivery.provider.test.crt
  build-test_key:
    file: ./vault/certs/build-test.delivery.provider.test.pem
  build-test_crt:
    file: ./vault/certs/build-test.delivery.provider.test.crt
  build-acc_key:
    file: ./vault/certs/build-acc.delivery.provider.test.pem
  build-acc_crt:
    file: ./vault/certs/build-acc.delivery.provider.test.crt
  build-prod_key:
    file: ./vault/certs/build-prod.delivery.provider.test.pem
  build-prod_crt:
    file: ./vault/certs/build-prod.delivery.provider.test.crt

services:
  build-dev.delivery.provider.test:
    container_name: build-dev.delivery.provider.test
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      BUILD_ENVIRONMENT: Dev
      ANSIBLE_TF_DIR: AppCICD
      ARM_SKIP_PROVIDER_REGISTRATION: 'true'
      RUNNER_TOKEN: '${RUNNER_TOKEN}'
    secrets:
      - source: dev_jenkins_secret
        target: /home/jenkins/secret-file.txt
    volumes: 
      - '~/images:/home/jenkins/images'
    depends_on:
      - jenkins.tooling.provider.test
      - gitea.tooling.provider.test
    networks:
      internal:
        ipv4_address: 172.16.12.2
        
  build-test.delivery.provider.test:
    container_name: build-test.delivery.provider.test
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      BUILD_ENVIRONMENT: Test
      ANSIBLE_TF_DIR: AppCICD
      ARM_SKIP_PROVIDER_REGISTRATION: 'true'
      RUNNER_TOKEN: '${RUNNER_TOKEN}'
    secrets:
      - source: test_jenkins_secret
        target: /home/jenkins/secret-file.txt
    expose:
      - '50000'
    networks:
      internal:
        ipv4_address: 172.16.12.3

  build-acc.delivery.provider.test:
    container_name: build-acc.delivery.provider.test
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      BUILD_ENVIRONMENT: Acc
      ANSIBLE_TF_DIR: AppCICD
      ARM_SKIP_PROVIDER_REGISTRATION: 'true'
      RUNNER_TOKEN: '${RUNNER_TOKEN}'
    secrets:
      - source: acc_jenkins_secret
        target: /home/jenkins/secret-file.txt
    expose:
      - '50000'
    networks:
      internal:
        ipv4_address: 172.16.12.4

  build-prod.delivery.provider.test:
    container_name: build-prod.delivery.provider.test
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      BUILD_ENVIRONMENT: Prod
      ANSIBLE_TF_DIR: AppCICD
      ARM_SKIP_PROVIDER_REGISTRATION: 'true'
      RUNNER_TOKEN: '${RUNNER_TOKEN}'
    secrets:
      - source: prod_jenkins_secret
        target: /home/jenkins/secret-file.txt
    expose:
      - '50000'
    networks:
      internal:
        ipv4_address: 172.16.12.5

