secrets:
  dev_jenkins_secret:
    file: ./Dev_secret.txt
  dev_jenkins_token:
    file: ./dev_runner_token
  test_jenkins_secret:
    file: ./Test_secret.txt
  test_jenkins_token:
    file: ./test_runner_token
  acc_jenkins_secret:
    file: ./Acc_secret.txt
  acc_jenkins_token:
    file: ./acc_runner_token
  prod_jenkins_secret:
    file: ./Prod_secret.txt
  prod_jenkins_token:
    file: ./prod_runner_token
  build-dev_key:
    file: ./vault/certs/build-dev.delivery.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.pem
  build-dev_crt:
    file: ./vault/certs/build-dev.delivery.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.crt
  build-test_key:
    file: ./vault/certs/build-test.delivery.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.pem
  build-test_crt:
    file: ./vault/certs/build-test.delivery.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.crt
  build-acc_key:
    file: ./vault/certs/build-acc.delivery.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.pem
  build-acc_crt:
    file: ./vault/certs/build-acc.delivery.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.crt
  build-prod_key:
    file: ./vault/certs/build-prod.delivery.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.pem
  build-prod_crt:
    file: ./vault/certs/build-prod.delivery.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.crt

services:
  build-dev:
    container_name: build-dev.delivery.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - BUILD_ENVIRONMENT=Dev
      - ARM_SKIP_PROVIDER_REGISTRATION='true'
      - DOMAIN_NAME_SL=${DOMAIN_NAME_SL}
      - DOMAIN_NAME_TL=${DOMAIN_NAME_TL}
      - ORG_NAME=${ORG_NAME}
    secrets:
      - source: dev_jenkins_secret
        target: /home/jenkins/secret-file.txt
      - source: dev_jenkins_token
        target: /home/jenkins/git-token.txt
    volumes: 
      - '~/images:/home/jenkins/images'
    depends_on:
      - jenkins
      - gitea
    networks:
      internal:
        ipv4_address: 172.16.12.2
    ports:
      - '16122:22'
  build-test:
    container_name: build-test.delivery.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - BUILD_ENVIRONMENT=Test
      - ANSIBLE_TF_DIR=AppCICD
      - ARM_SKIP_PROVIDER_REGISTRATION='true'
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - DOMAIN_NAME_SL=${DOMAIN_NAME_SL}
      - DOMAIN_NAME_TL=${DOMAIN_NAME_TL}
      - ORG_NAME=${ORG_NAME}
    secrets:
      - source: test_jenkins_secret
        target: /home/jenkins/secret-file.txt
      - source: test_jenkins_token
        target: /home/jenkins/git-token.txt
    volumes: 
      - '~/images:/home/jenkins/images'
    depends_on:
      - jenkins
      - gitea
    ports:
      - '16123:22'
    networks:
      internal:
        ipv4_address: 172.16.12.3

  build-acc:
    container_name: build-acc.delivery.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - BUILD_ENVIRONMENT=Acc
      - ANSIBLE_TF_DIR=AppCICD
      - ARM_SKIP_PROVIDER_REGISTRATION='true'
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - DOMAIN_NAME_SL=${DOMAIN_NAME_SL}
      - DOMAIN_NAME_TL=${DOMAIN_NAME_TL}
      - ORG_NAME=${ORG_NAME}
    secrets:
      - source: acc_jenkins_secret
        target: /home/jenkins/secret-file.txt
      - source: acc_jenkins_token
        target: /home/jenkins/git-token.txt
    volumes: 
      - '~/images:/home/jenkins/images'
    depends_on:
      - jenkins
      - gitea
    ports:
      - '16124:22'
    networks:
      internal:
        ipv4_address: 172.16.12.4

  build-prod:
    container_name: build-prod.delivery.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - BUILD_ENVIRONMENT=Prod
      - ANSIBLE_TF_DIR=AppCICD
      - ARM_SKIP_PROVIDER_REGISTRATION='true'
      - RUNNER_TOKEN'${RUNNER_TOKEN}'
      - DOMAIN_NAME_SL=${DOMAIN_NAME_SL}
      - DOMAIN_NAME_TL=${DOMAIN_NAME_TL}
      - ORG_NAME=${ORG_NAME}
    volumes: 
      - '~/images:/home/jenkins/images'
    depends_on:
      - jenkins
      - gitea
    secrets:
      - source: prod_jenkins_secret
        target: /home/jenkins/secret-file.txt
      - source: prod_jenkins_token
        target: /home/jenkins/git-token.txt
    ports:
      - '16125:22'
    networks:
      internal:
        ipv4_address: 172.16.12.5

