volumes:
  cust1_idp_data: null

secrets:
  cust1_idp_key:
    file: ../vault/certs/cust1-idp.iam.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.pem
  cust1_idp_crt:
    file: ../vault/certs/cust1-idp.iam.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}.crt

services:
  cust1_idp:
    container_name: cust1-idp.iam.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}
    build: .
    restart: unless-stopped
    hostname: cust1-idp
    expose:
      - "3890"
    ports:
      - "27170:17170"
    secrets:
      - source: cust1_idp_key
        target: /data/key.pem
      - source: cust1_idp_crt
        target: /data/cert.crt
    volumes:
      - ./data:/data
      - ./bootstrap:/bootstrap
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Amsterdam
      - LLDAP_URL=http://cust1-idp.iam.${CUST1_DOMAIN_NAME_SL}.${CUST1_DOMAIN_NAME_TL}:17170
      - LLDAP_ADMIN_USERNAME=${cust1_idp_admin_user}
      - LLDAP_ADMIN_PASSWORD=${local_admin_password}
      - LLDAP_LDAP_ADMIN_PASS=${local_admin_password}
      - LLDAP_HTTP_URL=http://cust1-idp.iam.${CUST1_DOMAIN_NAME_SL}.${CUST1_DOMAIN_NAME_TL}
      - LLDAP_JWT_SECRET =${CUST1_IDP_JWT_SECRET}
      - LLDAP_LDAP_BASE_DN=dc=${CUST1_DOMAIN_NAME_SL},dc=${CUST1_DOMAIN_NAME_TL}
      - LLDAP_LDAP_USER_DN = ${cust1_idp_admin_user}
      - LLDAP_LDAP_USER_EMAIL=${cust1_idp_admin_user}@${CUST1_DOMAIN_NAME_SL}.${CUST1_DOMAIN_NAME_TL}
      - LLDAP_LDAP_USER_PASS =${local_admin_password}
      - LLDAP_FORCE_LDAP_USER_PASS_RESET = FALSE
      - LLDAP_DATABASE_URL=postgres://${cust1_idp_db_user}:${cust1_idp_db_pwd}@cicdtoolbox-db.internal.${DOMAIN_NAME_SL}.${DOMAIN_NAME_TL}/cust1_idp
      - LLDAP_KEY_SEED = ${CUST1_IDP_KEY_SEED}
      - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET = false
      - LLDAP_SMTP_OPTIONS__SERVER = smtp.gmail.com
      - LLDAP_SMTP_OPTIONS__PORT = 587
      - LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION = TLS
      - LLDAP_LDAPS_OPTIONS__ENABLED = true
      - LLDAP_LDAPS_OPTIONS__PORT = 6360
      - LLDAP_LDAPS_OPTIONS__CERT_FILE = /data/cert.crt
      - LLDAP_LDAPS_OPTIONS__KEY_FILE = /data/key.pem
      - USER_CONFIGS_DIR=/bootstrap/user-configs
      - GROUP_CONFIGS_DIR=/bootstrap/group-configs
      - USER_SCHEMAS_DIR=/bootstrap/user-schemas
      - GROUP_SCHEMAS_DIR=/bootstrap/group-schemas
      - DO_CLEANUP=false
      - RUST_BACKTRACE=full
      - DOMAIN_NAME_SL=${CUST1_DOMAIN_NAME_SL}
      - DOMAIN_NAME_TL=${CUST1_DOMAIN_NAME_TL}
      - CUST1_DOMAIN_NAME_SL=${CUST1_DOMAIN_NAME_SL}
      - CUST1_DOMAIN_NAME_TL=${CUST1_DOMAIN_NAME_TL}
    networks:
      internal:
        ipv4_address: 172.16.8.110
    healthcheck:
      test: "curl --insecure -fSs http://cust1-idp.iam.${CUST1_DOMAIN_NAME_SL}.${CUST1_DOMAIN_NAME_TL}:17170/login"
      start_period: 60s
      interval: 5s
      timeout: 5s
      retries: 5

